layout_spectrum: 0.07474474
typography_spectrum: 0.7018739
color:
  saturation: 0.6422578
  lightness: 0.5047426
  brandStrength: 0.848694
  rhythmicContrast: 0.9025055
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
name: Jeep Mods
